Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -6,6 +6,9 @@ on:
     - cron: '*/30 * * * *'
   workflow_dispatch: # Cho phép bấm chạy thủ công trên GitHub
 
+permissions:
+  contents: write
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -31,7 +34,12 @@ jobs:
       run: |
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-        git add playlist.m3u
-        git diff-index --quiet HEAD || git commit -m "Auto updated playlist.m3u"
-        git push
-
+        if [ -f playlist.m3u ]; then
+          git add playlist.m3u
+          git diff-index --quiet HEAD || git commit -m "Auto updated playlist.m3u"
+          git push
+        else
+          echo "Error: File playlist.m3u không tồn tại!"
+          exit 1
+        fi
+        
